### ISSUE TITLE
Revise DSRA indicators

### ISSUE THREAD

**Issue by wkhchow** [OpenDRR/opendrr-data-store#54]
As per discussion with @tieganh @plesueur @mjourneay, changes to be revised for DSRA (for all building, sauid, b0, r1 if applicable):
- [x] sLm_Asset / sLm_Bldg - divided by replacement value instead of building number (what is replacement value?)
- [x] remove sH_RuppAbbr, resource sH_RupName from sH_RuppAbbr
- [x] sH_GMPE (https://github.com/OpenDRR/model-factory/issues/57) @drotheram 
- [x] remove SH_PGV
- [x] add SH_PGA
- [x] Recalculate all displaced household and shelter indicators with updated Et_SFHshld / Et_MFHshl values (https://github.com/OpenDRR/opendrr-data-store/issues/53).  Implement new intermediate tables to handle calculation of each portion of the equation to avoid confusion and for ease of pinpointing errors so that the final equation to calculate the displaced household / shelter can be reduced in size.

**Comment by tieganh** [comment]
More issues to follow up on - will edit this as I go:
- [x] the definition of displaced households from HAZUS uses probability of damage not displaced persons. But the DSRA's have 3/30/90/180/360 day values. Suggest we switch to single value. 
- [x] eCr_DisplRes90 - why named 'e' instead of 's'?
- [x] finish calculating shelter

**Comment by plesueur** [comment]
@tieganh: for item one in more issues to follow up on, yes, in general let's be consistent with HAZUS. Do you know where the 3/30 etc. value come from? Perhaps FEMA P-58 provides the curves to map from a single value, to the daily values?

**Comment by wkhchow** [comment]
- notes: replacement value used for sLm_Asset, SLmr_Bldg is replacement (str + nstr + cont) from exposure source and not from scenario values itself.
- @tieganh @plesueur the current way 3/30/90/180/360 displaced households is calculated is just showing the displaced households if the downtime is >3/30, etc.  I will just calculate the displaced households and we can decide whether or not to include the 3/30/90/180/360 after.
- I think Murray wanted to include eCr_DisplRes90 in DSRA, it stems from a same indicator from the PSRA indicators hence the 'eCr'.  We can change it back to s if preferred.

**Comment by tieganh** [comment]
Finished writing script to check DSRA indicators for a single SAUID. The output is attached for SAUID 59007373. @wkhchow if you want to check your results against mine then you can do it from that file, if you isolate that SAUID in QGIS/whatever tool you're using for your new runs. 

[DSRA_SAUID59007373.txt](https://github.com/OpenDRR/opendrr-data-store/files/7102224/DSRA_SAUID59007373.txt)

I ended up going back to basics on the HAZUS shelter calc, to understand what we were doing, and finding that the way we were implementing the 'demographic' section didn't quite check out. I opted to return that section to be based only on race by using visible minorities with averaged modifiers from black+hispanic+asian+nativeamerican. 

Code is attached with a txt filename because git wouldn't let me attach a python code.

[checkDSRA.py.txt](https://github.com/OpenDRR/opendrr-data-store/files/7102234/checkDSRA.py.txt)

**Comment by tieganh** [comment]
Big picture topics:

- [x] Ensure repair, reconstruction and downtime are renamed to repair, recovery, and interruption so they can be clearly linked to their definitions introduced by HAZUS (see image below, taken from Open File on scenarios). Described in [HAZUS Technical Manual](https://www.fema.gov/sites/default/files/2020-09/fema_hazus_earthquake-model_technical-manual_2.1.pdf) Section 15.2.4.
- [x] Change 'displaced' people to 'affected', which is a truer description. These calculations don't appear to be based on HAZUS, so there's no precedent we need to match. 
- [x] Simplifying shelter calculations, as explained in [Issue #75](https://github.com/OpenDRR/model-factory/issues/75)
- [x] Omit BCR and ROI? *Tentative*

<img width="620" alt="Screen Shot 2021-09-09 at 11 06 46 AM" src="https://user-images.githubusercontent.com/59665171/132739329-6aa87ef8-429a-4f6d-8f2c-7f8e5164d861.png">

**Comment by wkhchow** [comment]
@tieganh just clarifying
Currently mean_repair_time  = sC_Repair

**Comment by tieganh** [comment]
@wkhchow ok, and in [this table](https://docs.google.com/spreadsheets/d/1roIinl5BVe-7IX1QaXPICxiFd_mke7rUwM71rGk_Nmw/edit#gid=1138090907) it looks like construction was already changed to recovery. So then we'd just need to change 'downtime' to 'interruption'.

**Comment by wkhchow** [comment]
@tieganh for bullet 2 above  DisplRes_# I can change disrupted to affected vice versa, but we also have DisrupEmpl_# which I assume is disrupted, would it make sense to use disrupted for res instead of affected?  I think they have the same meaning do they not?  DisrupRes_# vs AfftRes_# ?

**Comment by wkhchow** [comment]
compilation of tasks from above and updates (applies to both building level/sauid):
- [x] sLm_Asset / sLm_Bldg  - updated with replacement value from exposure table
- [x] sH_RuppAbbr, - removed and kept SH_RupName
- [x] sH_GMPE, - https://github.com/OpenDRR/model-factory/issues/57
- [x] sH_PGV - removed
- [x] sH_PGA - added
- [x] Renamed all 'eC*' prefixes to 'sC*'
- [x] Renamed sC_Downtime to sC_Interruption to follow Hazus definition
- [x] Renamed sC_DisplRes_# to sC_AfftRes, this applies in building level, for sauid level our naming convention just becomes sCt_Res#, same goes for sC_DisrupEmpl# to Sct_Empl#.  Not sure if this needs to be changed?
- [x] BCR / ROI indicators - removed for now
- [x] sC_DisplHshld - updated calculation, removed 3/30/90/180/360
- [x] sCt_Shelter - updated calculation but still having having issues getting reasonable results, will need to follow up with @tieganh.  To add household income sources could be enhanced in census source files, (need to start another issue) to reflect the percentage distribution of incomes as right now we only have average income values per sauid.
- [x] Updated risk_profile_indicators gsheet to reflect all additional/removal/rename indicators mentioned above

**Comment by wkhchow** [comment]
All issues resolved pending sH_GMPE @drotheram to pull the GMPE file name into the source dsra file
https://github.com/OpenDRR/model-factory/blob/master/scripts/DSRA_outputs2postgres_lfs.py#L153

**Comment by wkhchow** [comment]
@tieganh GMPE issue has been resolved.  All changes completed.

**Comment by wkhchow** [comment]
Issue reopened to add new indicator @tieganh suggested.

- [x] MMI indicator, either pulled in as a precalculated column from shakemap file and would need to edit https://github.com/OpenDRR/model-factory/blob/11bf1dc701cd3ff317b97a3ef837f3b790236d6d/scripts/DSRA_runCreateTableShakemap.py to include the new column or calculate in the SQL side but need to add in code to figure out which equation to use (western/eastern canada)
- For western Canada equation 
MMI = 2.270 + 1.647*log(PGA) - 0.6 for log(PGA) <=1.6
MMI = -1.361 + 3.822*log(PGA) - 0.6 for log(PGA) > 1.6
where log is base-10 logarithm, and PGA is in units of cm/s^2.

- MMI indicator is placed on hold, will be commented out for now.

- [x] add CSD aggregation level https://github.com/OpenDRR/model-factory/issues/78

**Comment by wkhchow** [comment]
MMI indicator placeholder coded in but commented out for now until further notice.
